### ISSUE TITLE
Feature Request: Option to print the items to a new line following the string '→ var_name:'  and option to set this as default

### ISSUE THREAD

**Issue by flzn22** [sisoe24/Python-Easy-Print#1]
Summary: Option to replace '→ var_name:' with '→ var_name:\n'
Request is in title. Motivation is that there are cases where multiline objects are to be printed e.g. numpy arrays. Starting the print on the line after '→var_name:' will greatly improve readability for such objects. Presently, having to type in '\n' every time is too tedious to attempt, and I assume this extension was made for lazy people like me. (More generally, you could enable another `addCustomMessage2` extension setting for adding things after the colon too, but I don't know in general how useful this functionality would be.) 

Example:
`x = numpy.array([[1,2],[3,4]])`
Current print:
```
➡ x : [[1 2]
 [3 4]]
```
Suggested print:
```
➡ x :
 [[1 2]
 [3 4]]
```
Or even better (but not at all necessary):
```
➡ x : [[1 2]
       [3 4]]
```
P.S. Thank you for this extension; it provides an easy solution for noobs like me who aren't willing to the learn the syntax to make my own snippet. I've tried AutoHotKey options but this is much better than anything I could put together there.

**Comment by sisoe24** [comment]
Thanks for your feedback!

I could add an option print to a newline. That would be no problem.

I could also have the setting _Add Custom Message_ to be entirely up the user how to lay out the message, but it requires more thought because the unicode character must be included in order for some of the functionality to work.

The last suggestion snippet although it looks nice, it's not really possible from the extension point as it would require to insert tab/space characters when the object starts in a newline. That would be a job for a custom print function.

Also yes, you could manage with AHK but it depends of your needs. If you just want to have it for Visual Studio Code, a simple extension will do the trick far better (also a vscode snippet to a degree). If you would want to have a AHK script that does the print on every text for every app, then sure, would be the only choice (unless you want to learn each application API and make extensions for them 🤓 )

This would be a snippet example btw

```json
"print debug with newline": {
    "body": "print('$1 :\\n', $1)",
    "description": "quick print to a new line",
    "prefix": "pl"
  },
```

**Comment by sisoe24** [comment]
From `0.4.0` you have two new settings:

- Add a newline character inside the print: `print('-> x:\n, x)`
- Create a completely new statement where you can make it the way you want: `print('{text} \n👉', {text}, '👈')`. The statement call could also be a custom function.
